<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { changeMemberPassword, currentMember, memberLogout } from '../data/auth'
import { loadAllRankings } from '../data/store'
const router = useRouter(); const member = ref(currentMember()); const ranking = ref([]); const deferredPrompt = ref(null); const showInstallGuide = ref(false); const showPassword = ref(false); const showAccountMenu = ref(false); const passwordForm = ref({ oldPassword: '', newPassword: '', confirmPassword: '' }); const passwordMessage = ref(''); const passwordError = ref(''); let rankingTimer
const me = computed(() => ranking.value.find(user => user.id === member.value?.id) || member.value)
const myRank = computed(() => Math.max(ranking.value.findIndex(user => user.id === member.value?.id) + 1, 1))
function receiveInstallPrompt(event) { event.preventDefault(); deferredPrompt.value = event }
async function refreshRanking() { try { ranking.value = await loadAllRankings() } catch {} }
onMounted(() => { refreshRanking(); rankingTimer = window.setInterval(refreshRanking, 10000); window.addEventListener('beforeinstallprompt', receiveInstallPrompt); if (navigator.serviceWorker) navigator.serviceWorker.register('/member-sw.js').catch(() => {}) })
onUnmounted(() => { window.removeEventListener('beforeinstallprompt', receiveInstallPrompt); window.clearInterval(rankingTimer) })
async function install() { if (deferredPrompt.value) { await deferredPrompt.value.prompt(); deferredPrompt.value = null } else showInstallGuide.value = true }
async function installFromGuide() { if (deferredPrompt.value) { await deferredPrompt.value.prompt(); deferredPrompt.value = null; showInstallGuide.value = false } }
function openPassword() { showAccountMenu.value = false; showPassword.value = true }
function signOut() { memberLogout(); router.replace('/member/login') }
async function updatePassword() { passwordError.value = ''; passwordMessage.value = ''; if (passwordForm.value.newPassword.length < 6) { passwordError.value = '新密码至少 6 位'; return } if (passwordForm.value.newPassword !== passwordForm.value.confirmPassword) { passwordError.value = '两次输入的新密码不一致'; return } try { await changeMemberPassword(member.value.id, passwordForm.value.oldPassword, passwordForm.value.newPassword); passwordMessage.value = '密码修改成功'; passwordForm.value = { oldPassword: '', newPassword: '', confirmPassword: '' }; setTimeout(() => { showPassword.value = false; passwordMessage.value = '' }, 1000) } catch (error) { passwordError.value = error.message } }
</script>
<template><div class="member-app" @click="showAccountMenu = false"><header class="member-top"><div><p>顺八台球会所</p><h1>会员中心</h1></div><div class="member-account"><button class="member-badge" @click.stop="showAccountMenu = !showAccountMenu">{{ me?.name || '我的账号' }} <small>⌄</small></button><div v-if="showAccountMenu" class="member-account-menu" @click.stop><button @click="openPassword">修改密码</button><button class="member-signout" @click="signOut">退出登录</button></div></div></header><section class="member-hero"><span>我的积分</span><strong>{{ me?.points?.toLocaleString() || 0 }}</strong><small>PTS · 当前积分排名 {{ myRank }}</small></section><section class="member-section"><div class="member-section-head"><h2>积分排行</h2><span>全部 {{ ranking.length }} 人</span></div><div class="member-ranking-scroll"><div v-for="(user, i) in ranking" :key="user.id" class="member-rank-row"><span :class="['member-rank-no', `rank-${i + 1}`]">{{ i + 1 }}</span><span class="member-avatar">{{ user.name[0] }}</span><b>{{ user.name }}</b><strong>{{ user.points.toLocaleString() }}</strong></div></div></section><nav class="member-nav"><span class="active">⌂<small>首页</small></span><span @click="router.push('/member/pk/create')">♧<small>发起 PK</small></span><span @click="install">⌁<small>添加桌面</small></span></nav><div v-if="showPassword" class="member-modal-backdrop" @click.self="showPassword = false"><form class="member-password-modal" @submit.prevent="updatePassword"><button type="button" class="member-modal-close" @click="showPassword = false">×</button><p class="eyebrow">ACCOUNT SETTINGS</p><h2>修改密码</h2><label>原密码<input v-model="passwordForm.oldPassword" type="password" required /></label><label>新密码<input v-model="passwordForm.newPassword" type="password" minlength="6" required /></label><label>确认新密码<input v-model="passwordForm.confirmPassword" type="password" minlength="6" required /></label><p v-if="passwordError" class="member-error">{{ passwordError }}</p><p v-if="passwordMessage" class="member-success">{{ passwordMessage }}</p><button class="member-primary" type="submit">保存新密码</button></form></div><div v-if="showInstallGuide" class="member-modal-backdrop" @click.self="showInstallGuide = false"><section class="member-install-guide"><button class="member-modal-close" @click="showInstallGuide = false">×</button><p class="eyebrow">ADD TO HOME SCREEN</p><h2>添加到手机桌面</h2><button class="install-step install-android" :disabled="!deferredPrompt" @click="installFromGuide"><b>Android Chrome</b><span v-if="deferredPrompt">点击后弹出系统确认，确认即可添加。</span><span v-else>当前浏览器未提供安装权限，请使用 Chrome 并通过 HTTPS 访问。</span></button><div class="install-step"><b>iPhone Safari</b><span>点击底部分享按钮，选择“添加到主屏幕”。</span></div><div class="install-step"><b>微信内</b><span>请使用右上角菜单，在浏览器中打开后再添加。</span></div></section></div></div></template>
